FROM debian:unstable

RUN apt-get update && apt-get install -y \
    patch \
    bash \
    sed \
    wget \
    git \
    mercurial \
    dos2unix \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    unzip

RUN apt-get update && apt-get install -y \
    ca-certificates

WORKDIR /workspace

CMD ["/bin/bash"]
