name: Auto Build openresty

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

env:
  UPSTREAM_OWNER: "openresty"
  UPSTREAM_REPO: "openresty"

jobs:
  build-and-release:
    if: github.repository_owner == 'loongarch64-sources'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Check Version
        id: get_version
        run: |
          chmod +x ./scripts/get_version.sh
          LATEST_VERSION=$(./scripts/get_version.sh)
          # 1. 获取上游最新版本
          echo "Latest upstream version: $LATEST_VERSION"

          # 2. 检查本仓库是否已存在该 Release
          if gh release view "${LATEST_VERSION}" >/dev/null 2>&1; then
            echo "Release ${LATEST_VERSION} already exists. Skipping."
            echo "skip_workflow=true" >> $GITHUB_OUTPUT
          else
            echo "Release ${LATEST_VERSION} not found. Need to build."
            echo "skip_workflow=false" >> $GITHUB_OUTPUT
          fi

           # 3. 无论是否跳过，都输出版本号供后续步骤参考（如果需构建）
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Build Binary
        if: steps.get_version.outputs.skip_workflow != 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          chmod +x ./scripts/build_in_docker.sh
          ./scripts/build_in_docker.sh "$VERSION"

      - name: Upload Release
        if: steps.get_version.outputs.skip_workflow != 'true'
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          chmod +x ./scripts/release.sh
          ./scripts/release.sh "$VERSION"
